<?php

namespace EPSI\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends EntityRepository
{
    public function getCategories()
    {
        $categories = $this->getEntityManager()
            ->getRepository("EPSINewsBundle:categorie")
            ->findAll()
        ;

        return $categories;
    }
}
