<?php

namespace EPSI\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * newsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newsRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getAllNews()
    {
        $news = $this->getEntityManager()
            ->getRepository("EPSINewsBundle:news")
            ->findAll()
        ;

        return $news;
    }

    /**
     * @param Int $id
     * @return null|object
     */
    public function getNewsById($id)
    {
        $news = $this->getEntityManager()
            ->getRepository("EPSINewsBundle:news")
            ->find($id)
        ;

        return $news;
    }
}
